### ISSUE TITLE
Странные адреса файлов

### ISSUE THREAD

**Issue by m00nk** [MihailDev/yii2-elfinder-flysystem#1]
Использую Ваш пакет mihaildev/yii2-elfinder в связке с TinyMCE.

Конфигурация №1:

``` php
'root' => [
    'path' => 'uploads/images',
    'name' => 'Files'
],
```

все работает прекрасно, при выборе картинки в elFinder в диалог TinyMCE вставляется корректный относительный путь вида '/uploads/images/blog/some_image.jpg'

Конфигурация №2:

``` php
'root' => [
    'path' => 'images',
    'name' => 'Files',
    'class' => 'mihaildev\elfinder\flysystem\Volume',
    'component' => [
        'class' => 'creocoder\flysystem\LocalFilesystem',
        'path' => '@webroot/uploads'
    ]
],
```

При выборе файла в elFinder, вместо нормального относительного URL получаю вот такую строчку: 

```
/elfinder/connect?path=pages&_csrf=ZHFmakVISVYBOCwiJC0PYi8UXy4keAxvVgY8DBQPIw4NJytbERkvLw%3D%3D&cmd=file&target=fls1_aW1hZ2VzL3BhZ2VzL2Jsb2cvMjAxMi0wNy0xMC0xOC0zNi0yNS5qcGc
```

**Вопросы**
1. как заставить yii2-elfinder-flysystem возвращать корректные относительные URL, хотя бы для локальной файловой системы
2. почему в строку вставляется параметр _csrf, ведь он актуален только для сеанса работы в elFinder, а для файла, размещенного на странице сайта, это значение и не верное, и не нужное. Как убрать этот параметр?

**Comment by m00nk** [comment]
Нашел костыльное решение - если в конфиг класса Volume добавить параметр url, то адреса начинают формироваться правильно:

``` php
'root' => [
    'path' => 'images',
    'url' => '/uploads/images', // этот параметр обязателен
    'name' => 'Files',
    'class' => 'mihaildev\elfinder\flysystem\Volume',
    'component' => [
        'class' => 'creocoder\flysystem\LocalFilesystem',
        'path' => '@webroot/uploads'
    ]
],
```

Но такое поведение не удобно, т.к. при смене базового пути ('path' => '@webroot/uploads') придется вручную править все параметры 'url'... 

Есть идеи, как это обойти?

**Comment by MihailDev** [comment]
параметр url не обязателен если не требуется получать нормальный путь! в ином случае он начинает формировать ссылку которая будет открывать файл через элфаиндер (иногда это нужно)!

> Но такое поведение не удобно, т.к. при смене базового пути ('path' => '@webroot/uploads') придется вручную править все параметры 'url'... 

при смене базового пути вам в любом случае придётся везде менять пути или я чего то не понял!?
